version: '3'
services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  auth:
    build: ./auth
    container_name: auth
    networks:
      - backend
  nats:
    build: ./nats
    container_name: nats
    command: "--cluster_name NATS --cluster nats://localhost:6222 --http_port 8002 --port 4222 --config /etc/nats/nats-server.conf"
    ports:
      - 8002:8002
    networks:
      - backend
      - frontend
networks:
  backend:
    driver: bridge
  frontend:
    external: true
    name: infrastructure