version: '3'
services:
  gateway:
    build: ./gateway
    hostname: gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  auth:
    build: ./auth
    hostname: auth
    env_file:
      - .env
    networks:
      - backend
  nats:
    build: ./nats
    hostname: nats
    command: "--cluster_name NATS --cluster nats://localhost:6222 --http_port 8002 --port 4222 --config /etc/nats/nats-server.conf"
    ports:
      - 8002:8002
    networks:
      - backend
      - frontend
networks:
  backend:
    driver: bridge
  frontend:
    external: true
    name: infrastructure